### ISSUE TITLE
Unable to get it working on storybook 3.4.0

### ISSUE THREAD

**Issue by theogravity** [dump247/storybook-state#2]
I've noticed that your implementation depends on 3.2.x of the @storybook/addons package.

I'm unsure if it's related, but when I follow the install steps for this component using the @storybook `3.4.0-alpha.1` versions, I get 

"Accessing nonexistent addons channel" in the storybook UI.

**Comment by theogravity** [comment]
Yea, if I change all my `@storybook` package vers to 3.2.16, it works.

**Comment by dump247** [comment]
Did you also update `@storybook/addons` as well? That error can be the result of having more than one [addons version installed](https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel). I think `@storybook/addons` needs to be a peer dependency for storybook-state to prevent this issues.

**Comment by DTupalov** [comment]
Additional info for others, who have such problem as I had: if you get error with React Native application "Accessing nonexistent addons channel", and you have one version of `@storybook/addons` in your node_modules, then try to wrap your stories, that using `storybook-state` addon, with `setTimeout`

    setTimeout(() => {
      ...
      storiesOf('MyComponent', module)
       .add(
         'with state',
         withState({ isActive: false }, store => (
           <MyComponent {...store.state} />
        ))
      );
      ...
    }, 0)
