### ISSUE TITLE
Allow react 16 in peerDependencies

### ISSUE THREAD

**Issue by fernandopasik** [dump247/storybook-state#7]
would it be possible to allow react 16 in peerDependencies? Right now there's a warning when installing the package
`@dump247/storybook-state@1.4.0" has incorrect peer dependency "react@^15.6.0".`

**Comment by fernandopasik** [comment]
I propose to change it to:
```
"peerDependencies": {
    "react": ">=15.0.0"
  },
```

**Comment by mattfysh** [comment]
Oh hey @fernandopasik 👋

**Comment by dump247** [comment]
Is `>=15.0.0` really a good idea? How can I be sure it's going to work with react 17, 18, etc? Would `^15.0.0 || ^16.0.0` be reasonable?

**Comment by fernandopasik** [comment]
Seems reasonable @dump247

**Comment by dump247** [comment]
Should be resolved in [v1.5.0](4fdada2f13946a908bd08ba16984b492f2f8c865). I used `^15.5.0 || ^16.0.0` since the project uses the `prop-types` module, which was introduced in [react 15.5](https://reactjs.org/docs/typechecking-with-proptypes.html).

**Comment by fernandopasik** [comment]
Thanks!
